// <auto-generated />
namespace Entaria.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class reader : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(reader));
        
        string IMigrationMetadata.Id
        {
            get { return "201404111131101_reader"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
