// <auto-generated />
namespace Entaria.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class transactions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(transactions));
        
        string IMigrationMetadata.Id
        {
            get { return "201404181039317_transactions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
