// <auto-generated />
namespace Entaria.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Hugh_03 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Hugh_03));
        
        string IMigrationMetadata.Id
        {
            get { return "201404111643264_Hugh_03"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
